
############################################################################
# apps/examples/espcli/Makefile
############################################################################

include $(APPDIR)/Make.defs

# espcli built-in application info

PROGNAME  = $(CONFIG_EXAMPLES_ESPCLI_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_ESPCLI_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_ESPCLI_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_ESPCLI)

# espcli Example

MAINSRC = espcli_main.c

include $(APPDIR)/Application.mk
